### ISSUE TITLE
make it possible to set zerolog as the logger for OpenTelemetry

### ISSUE THREAD

**Issue by vroldanbet** [jzelinskie/cobrautil#16]
when a user misconfigures opentelemetry via cobrautil flags, the otel-go library will surface errorrs using stdout.

OTel offers API to set a custom logger that complies with the `go-logr` facade interface https://pkg.go.dev/go.opentelemetry.io/otel#SetLogger

it would be desirable to make it possible to set zerolog as the logger for OTel

**Comment by jzelinskie** [comment]
I think this package in general should just adopt go-logr. I tried instead to avoid logging altogether, but zerolog slipped in.

**Comment by vroldanbet** [comment]
Agreed, will close and open an issue to adopt logr
