### ISSUE TITLE
gRPC flag support ca path?

### ISSUE THREAD

**Issue by oslook** [jzelinskie/cobrautil#2]
in v0.0.7, we can see
// GrpcServerFromFlags:
// - "$PREFIX-addr"
// - "$PREFIX-tls-cert-path"
// - "$PREFIX-tls-key-path"
// - "$PREFIX-max-conn-age"

In our case, it need use the ca cert in gRPC server. Could you add this flag?

**Comment by jzelinskie** [comment]
That's `$PREFIX-tls-cert-path`, but you'll need both the cert and the key to secure the endpoint.

**Comment by oslook** [comment]
> 

yes, we will config both cert and key to secure the endpoint.
I our case, the cert contain the ca cert and tls cert, so is it need the flag like "$PREFIX-ca-cert-path" and "$PREFIX-tls-cert-path"?
